### PR TITLE
Add support for external icons

### PR DESCRIPTION
**Pull request by distantnative**
Fixes k-next/starterkit#363

Mainly for plugin developers to include their own icons, since we will not be able to cover all with the ones we include.

```
<kirby-icon type="https://raw.githubusercontent.com/leungwensen/svg-icon/master/src/zero/add-folder.svg" />
```

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I would handle that differently. With the img tag there's no control over the color of the icon, which is probably not very helpful. I also think this doesn't really have a high prio atm.

**Comment by distantnative** [comment]
I am not sure about the prio to be honest. If we want most plugin developers to move their plugins over for 3.0 (and not to wait till 3.1, 3.2...), they likely will need a way to add their own icons instead of our limited set.

**Comment by lukasbestle** [comment]
External icons aren't that great anyway because they are not consistent with the built-in ones. Maybe we should ship the Panel with the whole icon set and lazy-load all icons that we don't use ourselves in the Panel.

**Comment by distantnative** [comment]
@lukasbestle totally! with external ones I meant other icons from the same set which we just don't include directly

**Pull request closed without merging**
