### PR TITLE
Add unsaved data indicator

### PR DESCRIPTION
**Pull request by distantnative**
Fixes k-next/starterkit#21

screen shot 2017-10-31 at 23 04 53

### CODE REVIEW

**Comment by distantnative** [comment]
@bastianallgeier the sticky `kirby-notice` could also be used as a save button as requested by some others

**Comment by bastianallgeier** [comment]
I really like the idea, but I think we should find something different than the borders. They could easily create issues for more complex fields with different layouts. Maybe the yellow color + some icon for the label?

**Comment by distantnative** [comment]
I realized myself, that I would like to solve this in a different way, but that also would connect much more to the draft feature (cause what happens with unsaved fields in the current version once you switch pages, that would negate everything). The better version would be to constantly auto-save to the discussed draft file (or in any way we will implement that feature) and then only  compare the auto-saved and the actual saved/published file and based on this display a notice e.g. like "Unpublished changes" – cause as I see it now, with the auto-save/draft feature, there should never be the case of unsaved data, only unpublished/uncommited data (or similar). What do you think, @bastianallgeier?

**Comment by lukasbestle** [comment]
That idea with constant auto-saving sounds great! That would also reduce a lot of the "I was logged out and now all my work is lost" issues (as the auto-saving would be part of the draft, not the session).

Also we'd then never need a save button, only a publish button. Saving would always happen in the background like in Google Docs/Dropbox Paper.

One possible issue: We need to make sure that only one person can update the same page at a time. Otherwise they'd be constantly overwriting the work of the other user.

**Comment by distantnative** [comment]
@lukasbestle exactly. but having the draft (and I guess we would need to include the editing user) and noticing that the draft is never than the published version, we could automatically lock the page for other users. Or something like that.

**Comment by lukasbestle** [comment]
Sounds good. But we‘d need a button to force unlock. And also we‘d need a detection if the user with the lock is still active on that page. Maybe an automatic unlock after five minutes without auto-save?

**Comment by bastianallgeier** [comment]
I thought about the same solution. We should start working on the draft/version implementation pretty quickly to take it to a stable level soon. I have some experience with locking/unlocking for a client project already, so I'm sure we can build something cool around this. 

My idea so far is, that a new page is always created as draft first. Once a page has been published for the first time, we would then create a new version when the page is being edited. I was thinking about introducing new drafts and version folders. The drafts folder would contain all drafts for non-existing subpages and the versions folder would contain versions of the current page. 

```
.drafts
.versions
```

Within those are additional subfolders for drafts and versions:

```
.drafts
- article-a
- article-b
```

```
.versions
- 20171112-121212
- 20171113-121212
```

Versions and Drafts are always complete folders including all the files and images + text files for a page. They really represent a full state of a page. The actual folder can be swapped out with their content by simply replacing it. 

I'm not entirely sure if we should have multiple versions or only allow single versions. But in theory we could always store the last version you can roll back to and the currently edited version. So there would be three states:

1. the past
2. the present
3. the future

We could even call the version folders like that: 

```
.versions
- past
- future
```

Future versions would also handle locking. If there's a future version, we lock the form for other editors. 

Here are a couple scenarios around locking: 

- Editor A enters a page, no future version exists so far, a new future version is being created, auto-save stores everything there
- Editor B enters a page, a future version by Editor A exists, the form is locked. The panel pulls for changes every 5 seconds, so as soon as the form is being unlocked by Editor A, Editor B will see the change
- Editor A publishes their changes, the future version is being removed and the form is unlocked. 
- ...or Editor A leaves the page without publishing, the panel asks if they don't want to publish the changes. Editor A confirms and leaves the page without publishing. The future version will be deleted and the form will be unlocked. Editor B is now able to edit.

I hope this all makes sense. 

The good thing is, that it's very easy to ignore those folders and all their content in Git or VC in general.

**Comment by distantnative** [comment]
So past would be always the version previous to the last published changes?

> ...or Editor A leaves the page without publishing, the panel asks if they don't want to publish the changes. Editor A confirms and leaves the page without publishing. The future version will be deleted and the form will be unlocked. Editor B is now able to edit.

What if Editor A just closes the window, quits the browser, computer crashes after having made changes?

**Comment by lukasbestle** [comment]
> What if Editor A just closes the window, quits the browser, computer crashes after having made changes?

We could keep the future version but remove the assignment to editor A. The next user who opens the page in the Panel would claim the lock.
So basically we could offer this as an option when leaving the page: „Throw edits away“, „Keep edits“, „Publish edits“ or „Cancel“ (back to editing).

And in case editor A is forcefully logged out because of a computer crash or something, there could always be a „force unlock“ button with a warning modal.

**Pull request closed without merging**
