### PR TITLE
 Using source queries for field options

### PR DESCRIPTION
**Pull request by distantnative**
Needs https://github.com/k-next/kirby/pull/24

New field options syntax:

**from url (as before):**
```
…
options: url
url: JSONURL
```

**from source query**
```
…
options: source
source:
  query: page.children.visible
  key: …
  value: …
```

```
…
options: source
source:
  query: file.tagfield
```

```
…
options: file.tagfield
```

```
…
options: users.filterBy('role', 'admin')
```

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Not entirely sure we should introduce one more option or rather replace the old query option with this new one.

**Comment by distantnative** [comment]
@bastianallgeier 
This new option actually already replaces two of the old options (query and field) in this PR ;)

**Comment by distantnative** [comment]
But I just realized that the regular expression might break some other scenarios (who would have thought!), sigh...

**Comment by bastianallgeier** [comment]
@distantnative should I still merge it and we take care of that in another issue?

**Comment by distantnative** [comment]
@bastianallgeier I guess that would be a good way instead of bloating up the PR. It actually seems to be quite a tricky thing to achieve. Maybe we have to put down some rules for parameters in queries (type of quotes, no arrays or so)...

**Comment by distantnative** [comment]
@bastianallgeier added a better option that seems to work as long as single quotes are used to wrap strings in parameters, not double quotes

**Pull request merged**
