### PR TITLE
Adding a flag to disable sentry

### PR DESCRIPTION
**Pull request by nocksock**
Adds a simple boolean flag to disable sentry. Useful for local development.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Would be great if we could set this via window. Then we can inject the setting with PHP and load it from the Kirby config later.

**Comment by bastianallgeier** [comment]
… or even from an .env file

**Comment by nocksock** [comment]
Setting it via window would be neat. Could easily be set via PHP then too. I'm going to look into this later.

**Comment by distantnative** [comment]
@bastianallgeier ready to be merged

**Pull request merged**
