### PR TITLE
Refactor plugin registry + registering translation strings

### PR DESCRIPTION
**Pull request by distantnative**
Fixes k-next/starterkit#273

```javascript
panel.plugin("myPlugin", {
  components: {
    "kirby-hello": {
      template: `<div>Hello!</div>`
    }
  },
  fields: {
    "currency": {
      template: `
        <kirby-field v-bind="$props" prefix="€">
          <input type="number" :value.number="state" @input="input($event.target.value)">
          <kirby-dropdown slot="icon">
            <kirby-button tabindex="-1" icon="angle-down" @click="$refs.dropdown.toggle()" />
            <kirby-dropdown-content ref="dropdown" align="right">
              <kirby-dropdown-item icon="add" @click="input(15.00)">€ 15.00</kirby-dropdown-item>
              <kirby-dropdown-item icon="add" @click="input(30.00)">€ 30.00</kirby-dropdown-item>
              <kirby-dropdown-item icon="add" @click="input(45.00)">€ 45.00</kirby-dropdown-item>
            </kirby-dropdown-content>
          </kirby-dropdown>
        </kirby-field>
      `
    }
  },
  menuItems: {
    "test": {
      label: "Custom view"
    }
  },
  sections: {
    "test": {
      props: {
        config: Object
      },
      data () {
        return {
          message: this.config.message
        }
      },
      methods: {
        submit () {
          this.$refs.dialog.close();
        }
      },
      computed: {
        fields () {
          return [
            {
              label: 'Message',
              name: 'message',
              type: 'text'
            }
          ];
        }
      },
      template: `
        <section>
          <kirby-headline>
            {{ config.headline }}

            <kirby-button-group slot="options">
              <kirby-button @click="$refs.dialog.open()" icon="cog"></kirby-button>
            </kirby-button-group>
          </kirby-headline>
          <kirby-box @click="$refs.dialog.open()">
            {{ message ? message : 'Please change me …' }}
          </kirby-box>

          <kirby-dialog ref="dialog" button="Ok" @submit="submit">
            <kirby-form :fields="fields" :values="$data"></kirby-form>
          <kirby-dialog>
        </section>
      `
    }
  },
  translations: {
    "en_US": {
      "label": "Utter nonsense" // plugin.myPlugin.label
    },
    "de_DE": {
      "label": "Völliger Quatsch"
    }
  },
  use: {
    "myLibrary": {}
  }
});
```

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Could you write some short docs how this would be used in plugins? I'm a bit lost.

**Comment by distantnative** [comment]
Sure! Basically…

```javascript

panel.locales("en_US", {
  "plugin.currency.label": "Currency",
});

panel.locales("de_DE", {
  "plugin.currency.label": "Währung",
});

panel.field("currency", {
  template: `<div><h3>{{ $t('plugin.currency.label') }}</h3>`
})
```

But writing this just got me thinking if `translations` would be a better name and it could even work like:

```javascript
panel.translations("PLUGINNAME", {
  "en_US": {
    "plugin.currency.label": "Currency"
  },
  "de_DE": {
    "plugin.currency.label": "Währung"
  }
});

// all string registered this way get automatically prefixed with `plugin.PLUGINNAME.`

```

What do you think?

**Comment by bastianallgeier** [comment]
Translations is indeed a better name. I think we should also use it on the backend.

**Comment by bastianallgeier** [comment]
I was just thinking if we should unify the way plugins are registered in the panel and in the backend. Maybe a good thing to write down a couple more notes in Notion for it?

**Comment by distantnative** [comment]
@bastianallgeier not sure what direction you want to unify them? do you want to kick off the notes in Notion and then I chime in adding to them?

**Comment by distantnative** [comment]
@bastianallgeier I refactored the plugin registry to better match how plugins are registered on the PHP part. You can see the concept in the PR description.

**Comment by distantnative** [comment]
@bastianallgeier name as first argument in the backend sounds good. so we can get rid of the `extends` key, keeps that array flatter.

**Pull request merged**
