### PR TITLE
 Add CalendarInput to DateField

### PR DESCRIPTION
**Pull request by distantnative**
Blocked by https://github.com/k-next/panel/pull/273

screen shot 2017-12-09 at 19 54 18

### CODE REVIEW

**Comment by distantnative** [comment]
Waiting for other PRs to be merged first

**Comment by bastianallgeier** [comment]
I actually think we shouldn't create another field for that but add the calendar to the date and datetime fields.

**Comment by distantnative** [comment]
I was thinking about the same, but I feel like depending on your use case a calendar might be nice to see what weekday the date actually is etc. But in other use cases, entering a lot of dates, it might be better to have the fastest way possible. And that would be rather the current date field with select inputs.

**Comment by lukasbestle** [comment]
I agree that this should rather be a blueprint option for the date and datetime fields. Of course only, if those fields don't become a monster by doing that. Otherwise it's alright to have a separate field for this.

**Comment by distantnative** [comment]
I would say, combining both fields to make it a blueprint option would be resulting in quite a monster.

**Comment by distantnative** [comment]
@bastianallgeier @lukasbestle 
Changed it to include the calendar as a variant of the DateField, activated by setting `display: calendar` as option in the blueprint.

**Comment by distantnative** [comment]
First, https://github.com/k-next/panel/pull/273 should be merged and then this PR needs some changes to follow the fields consistency

**Comment by distantnative** [comment]
This is still quite buggy (e.g. today button not working, changing calender display via the select fields etc.), but could you have a look if it is in the right direction, @bastianallgeier?

**Comment by bastianallgeier** [comment]
Wouldn't it be much cooler if we keep the select boxes, but make it work that the calendar widget can set the select options correctly? That would be the way I think would be most consistent.

**Comment by distantnative** [comment]
@bastianallgeier and only opening the calendar view via click on the icon?

**Comment by bastianallgeier** [comment]
@distantnative yep.

**Comment by bastianallgeier** [comment]
In my opinion the select boxes are a pretty good for entering the date consistently and in an accessible way. The calendar widget is more like a add-on, to help with date selection.

**Comment by distantnative** [comment]
I like the idea. Also gets rid of having any additional `display` option – big fan of that :D

**Comment by distantnative** [comment]
@bastianallgeier done!

**Comment by bastianallgeier** [comment]
That looks soooooo cool :D

**Pull request merged**
