### PR TITLE
 Change to Plugin Registry and Loader; add View and MenuButtons plugins

### PR DESCRIPTION
**Pull request by distantnative**
I keep running into the problem, that the wildcard `*` route catches the url instead of the newly registered plugin route. However, when using `$router.resolve()` the path gets resolved correctly to the plugin route. I have tried a lot but no succcess, maybe you, @bastianallgeier, can have a look at this and see if you can figure this out.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Maybe we need to rethink plugin installation. We could load them all before panel.js and they all would need to register a function instead of directly registering an object. 

So instead of 

```js
panel.field('range', {});
```

it would be 

```js
panel.field('range', () => {
  return {
  }
});
```

This would make it possible for us to load all registered plugins in our panel.js, inject vue and other dependencies into the callback and get the routes of plugins before the router is initialized. So we can inject those routes before we register the wildcard.

**Comment by distantnative** [comment]
Yea, actually that sounds like a good idea. I will try to make it work :)

**Comment by distantnative** [comment]
Ready to be reviewed, @bastianallgeier 
Can be used with this non-sense demo in the starterkit/panel.js:
```javascript
panel.view('test', {
  template: '<kirby-view>Hello world!</kirby-view>',
  created () {
    this.$store.dispatch('isLoading', false);
  }
})

panel.menuButton('test', {
  link: '/plugin/test',
  icon: 'globe',
  label: 'Hello World'
})
```

**Comment by bastianallgeier** [comment]
Hm, seems like a merged it too early. Can't get it to run on my machine at all.

**Pull request merged**
