### PR TITLE
Code splitting

### PR DESCRIPTION
**Pull request by distantnative**
Already includes: https://github.com/k-next/panel/pull/232
Requires: https://github.com/k-next/kirby/pull/16

### CODE REVIEW

**Comment by distantnative** [comment]
Since we register every component as global component (even the smallest, instead of importing them only in their parent components), only picking common UI components or fields would result in some chunks for these with the same size as now and everything else in one big file again.

**Comment by bastianallgeier** [comment]
And what about keeping everything really simple for the UI kit and just create one file out of it? I planned to do that initially because it means we could also provide it as standalone file for plugin devs to play with in codepen or anywhere else.

**Comment by distantnative** [comment]
I reduced it to a version of three main js files (vendor, ui and panel) with additional dynamic code splitting on views (which I guess is the minimum):

screen shot 2017-11-02 at 09 48 07

I would say we could split a bit more if we keep it to the panel part (e.g. dialogs). There will be still many small js files then, but those are loaded dynamically and as long as the UI kit is one single js file to be used e.g. in codepen, it shouldn't matter how many files the panel will end up. What do you think?

**Comment by distantnative** [comment]
Small additional issue: Right now vuedraggable and sortable end up in the `vendor.js`, even though they are also used by the UI TagsField. However, including those library just for the TagsField in the ùi.js`seems quite the high cost.

**Pull request closed without merging**
