### PR TITLE
Load file meta fields from API

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
That's cool! But I would actually love to have file fields defined for each individual file collection. So for example the cover image could have completely different fields than gallery images or other files.

**Comment by distantnative** [comment]
I see, so the blueprint would look like this?

```
layout:
  -
    width: 2/3
    sections:
      -
        type: fields
       …
  -
    width: 1/3
    sections:
      -
        headline: Cover
        type: files
        …
        fields:
        -
          name: author
          type: text
        -
          …
```

**Comment by bastianallgeier** [comment]
Yes, exactly!

**Comment by distantnative** [comment]
How would you define to which section the current FileView belongs? Cause a file can currently be part of several collections/sections.

**Comment by lukasbestle** [comment]
It would then need the fields from all collections the file is in (basically merge the field definitions). Maybe we could somehow group the fields visually by collection?

**Comment by distantnative** [comment]
@bastianallgeier @lukasbestle 
I added with https://github.com/k-next/kirby/pull/11 merging all file meta fields across collections. Yet without visual indicator what fields belong to which section/collection.

**Comment by bastianallgeier** [comment]
My idea for files was, that we introduce a new group feature. This is needed all the time. A group would be "gallery", "cover", "downloads" or anything like that. The group would be defined when using the files section and it will always be passed to the file url in the panel. So for example: 

`/pages/projects/project-a/files/something.jpg/in/cover`

Not sure if this is the final format, but a rough first idea. Like this it would be easy to load the right set of meta fields.

**Comment by lukasbestle** [comment]
Sounds great as well. But then we'd need a clear visual indicator in the file view that shows which group's fields are currently edited.
But an advantage would be that the pagination would work automagically (pagination within that group only).

**Comment by bastianallgeier** [comment]
I solved this for the Alpha by adding the groups. It's not entirely perfect yet, but pretty convincing already.

**Pull request closed without merging**
